### ISSUE TITLE
The caller does not have permission

### ISSUE THREAD

**Issue by ladevan** [vperezb/google-api-support#1]
Hi,

First, thank you so much for developing this, very convenient. I tried to test it after creating a credential, however, it shows "The caller does not have permission". Not sure how to solve it.

**Comment by vperezb** [comment]
Hi @ladevan , many thanks for opening the issue this feedback helps me a lot to try to improve this small project! For the problem I there's a couple of things coming up on my brain.
1- You need to enable the API in the project where you've just created the credentials
2- You need to share the file with your service account mail address (you can find it the Service Account section in your project in console.cloud.google.com.

It may be more visual in the 6, 7, 8 slides of this presentation https://docs.google.com/presentation/d/1p0ouOWDZxX7QemDeNk976KiDp6ooWYEc9DhMcuOpY7U/edit?usp=sharing

I hope this information helps you come with the right solution if not, don't hesitate to keep notifying me and if yes, was a pleasure!

Many thanks!

**Comment by ladevan** [comment]
Hi @vperezb , thanks for your quick reply. I think the part I am missing is to share the service account email for the documents that I want to modify. After sharing with my service account email, I can access via API.

But I think this approach is not that convenient since you need to share all the documents that you want to operate via API, right? I found another authentication method [https://developers.google.com/slides/quickstart/python](here), I used to try this approach, it doesn't require share documents with an email, do you think you can add an option to use this authentication?

Best,

Dengyu

**Comment by vperezb** [comment]
Hi @ladevan, thanks for your insights and for the suggestion. 

You're right this method can't be as convenient as the other method you shared me as credential management and authentication is not trivial. I'll work on adding the method shown in the quickstart as an alternative method into the Module so the user can choose the way they want to authenticate.


By now, as a quick win, you can share for example the folder containing all your "editable" docs in order to give them permission to all of them.

And as a bonus track, service credentials simplify the setup when you want to use these tools in an environment fully programmatically (without a mouse). 

But as you are exposing, adding this method you shared will make the setup easier, it's a really good point.

As this Issue is already closed, I'll create a new one to track it well! 

Many thanks for your feedback

Víctor

**Comment by vperezb** [comment]
As closing statement:
The issue can be solved by **sharing the document we are trying to edit with the service account email** that can be found in the  Service Account section in your project in console.cloud.google.com .

**Comment by silvia-ventoruzzo** [comment]
Hi @vperezb,
any update regarding the implementation on the other authentication method?
I am running into the same issue right now and it would be a big help to have an alternative that doesn't force me to share each document with the service account.
Thanks in advance.

**Comment by vperezb** [comment]
As was out of "my usecases" I invested less effort on this point but as it's not the first time someone faces this problem I'll take a look this following week.

**Comment by vperezb** [comment]
Marking as closed to use only issue #2
